# Generated by Django 5.2.8 on 2025-11-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_farm_galleryimage_message_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="snippet",
            new_name="message",
        ),
        migrations.AddField(
            model_name="message",
            name="receiver",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
