# Generated by Django 5.2.8 on 2025-11-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_summary_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default='', upload_to='gallery/'),
        ),
    ]
