# Generated by Django 5.2.8 on 2025-12-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_galleryimage_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farm',
        ),
        migrations.AddField(
            model_name='product',
            name='farms',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.farm'),
        ),
    ]
