# Generated by Django 5.2.8 on 2025-12-14 14:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_product_farm_product_farms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user who owns this cart.', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product in the cart.', validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(help_text='The cart this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.cart')),
                ('product', models.ForeignKey(help_text='The product being added to the cart.', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='app.product')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(help_text='The blog post that was favorited.', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='app.blogpost')),
                ('user', models.ForeignKey(help_text='The user who favorited the blog post.', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Blog',
                'verbose_name_plural': 'Favorite Blogs',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'blog_post')},
            },
        ),
    ]
