# Generated by Django 5.2.8 on 2025-12-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_cartitem_cart_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='favoriteblog',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteblog',
            unique_together=set(),
        ),
    ]
