# Generated by Django 5.2.8 on 2025-11-25 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_review_name_product_creator_review_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="summary",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="message",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="creator",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="text",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="message",
            name="name",
        ),
        migrations.AddField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("sender", models.F("receiver")), _negated=True),
                name="sender_is_not_receiver",
            ),
        ),
    ]
