# Generated by Django 5.2.8 on 2025-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Gardening', 'Gardening'), ('Recipes', 'Recipes'), ('Farming', 'Farming')], default='Gardening', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Eggs', 'Eggs'), ('Goods', 'Goods'), ('Meat', 'Meat'), ('Fruit', 'Fruit')], default='Goods', max_length=100),
        ),
    ]
