# Generated by Django 5.2.8 on 2025-12-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_chat_remove_message_sender_is_not_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs_reviews', to='app.blogpost'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='app.product'),
        ),
    ]
